name: Annotation
on: push
jobs:
  log:
    runs-on: self-hosted
    steps:
      - run: echo "::error::This is an error"    # Errorレベルのアノテーション
      - run: echo "::warning::This is a warning" # Warningレベルのアノテーション
      - run: echo "::notice::This is a notice"   # Noticeレベルのアノテーション
