name: Missing share data
on: push
jobs:
  share:
    runs-on: self-hosted
    steps:
      - run: export RESULT="hello" # 次のステップへ環境変数で値を渡そうとしている
      - run: echo "${RESULT}"      # しかし環境変数を参照しても空文字になる
