name: Secret scan
on: pull_request
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |                                             # Secretlintの実行
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" \
          secretlint/secretlint secretlint --maskSecrets '**/*'
