name: Share job data
on: push
jobs:
  before:
    runs-on: self-hosted
    steps:
      - id: generate                                   # ステップのID
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}" # ステップレベルの出力値
    outputs:
      result: ${{ steps.generate.outputs.result }}     # ジョブレベルの出力値
  after:
    runs-on: self-hosted
    needs: [before]                                    # 依存するジョブIDの指定
    steps:
      - env:
          RESULT: ${{ needs.before.outputs.result }}   # 依存ジョブの出力値を参照
        run: echo "${RESULT}"
